-- return {
--   'akinsho/bufferline.nvim',
--   dependencies = {
--     'nvim-tree/nvim-web-devicons',
--   },
--   opts = {
--     options = {
--       mode = 'buffers',
--       tab_size = 24,
--       separator_style = 'thick',
--       diagnostics = 'nvim_lsp',
--       -- diagnostics_update_in_insert = true,
--     },
--   },
-- }
return {}
